### PR TITLE
Change Variance to St. Dev.

### LINKED ISSUE #147: Incorrect labelling in "Temperature Variations" test case
minor typographic error: the "Temperature variations" exercise says "variance" in the output tests but the question asks for standard deviation.

### PR DESCRIPTION
**Pull request by Vismai-Khanderao**
Resolves #147

### CODE REVIEW

File: src/static/visualization/temperature-variations.js [hunk 1]
```diff
@@ -59,26 +59,26 @@ function plot_temp_mean_variance(id, data) {
...
+        text: 'mean - st_dev / 2'
     }
 
-    var trace_variance_max = {
+    var trace_st_dev_max = {
         x: months,
-        y: Array(months.length).fill(mean + variance / 2),
-        name: 'variance',
+        y: Array(months.length).fill(mean + st_dev / 2),
+        name: 'Standard Deviation',
```
Comment (ali-ramadhan) [inline src/static/visualization/temperature-variations.js:76]: Just making it lowercase so it matches the other names in the legend.

```suggestion
        name: 'standard deviation',
```

**Review by ali-ramadhan — APPROVED** [review]
Looks good to merge! Thanks for fixing this @Vismai-Khanderao!

You can also put "Resolves #147" in your original comment or any other comment in this PR and the issue will automatically be closed when this PR gets merged.
